"""Gold-set evaluation (plan 4.6). Every matcher change runs this in CI; regressions fail the build.

The bundled gold set (tests/gold/pairs.json) is SYNTHETIC: generated by scripts/gen_gold.py from a
hand-written catalogue with retailer-style name variations. It guards against regressions but does
NOT prove real-world accuracy - replace/extend it with audited real listing pairs once sources are
approved (plan 4.6 asks for 1,000 labelled pairs).
"""

import json
from pathlib import Path
from typing import Any

from .attributes import extract
from .scoring import AUTO_THRESHOLD, REVIEW_THRESHOLD, score_pair

DEFAULT_GOLD = Path(__file__).resolve().parents[2] / "tests" / "gold" / "pairs.json"
BASELINE = DEFAULT_GOLD.with_name("baseline.json")


def evaluate(path: Path | None = None) -> dict[str, Any]:
    pairs = json.loads((path or DEFAULT_GOLD).read_text(encoding="utf-8"))
    tp = fp = fn_auto = 0
    cand_tp = cand_fn = 0
    same_lang_pos = same_lang_auto = 0
    false_auto: list[dict[str, Any]] = []
    missed: list[dict[str, Any]] = []
    for p in pairs:
        a = extract(p["a"]["name"], p["a"].get("size"))
        b = extract(p["b"]["name"], p["b"].get("size"))
        s = score_pair(a, b)
        auto = s.ok and s.score >= AUTO_THRESHOLD
        cand = s.ok and s.score >= REVIEW_THRESHOLD
        if p["same"]:
            cross = p.get("cross_language", False)
            if not cross:
                same_lang_pos += 1
                same_lang_auto += int(auto)
            if auto:
                tp += 1
            else:
                fn_auto += 1
            if cand:
                cand_tp += 1
            else:
                cand_fn += 1
                if len(missed) < 15:
                    missed.append({"a": p["a"], "b": p["b"], "score": s.score, "reject": s.reject})
        elif auto:
            fp += 1
            if len(false_auto) < 15:
                false_auto.append({"a": p["a"], "b": p["b"], "score": s.score})
    positives = tp + fn_auto
    return {
        "pairs": len(pairs),
        "positives": positives,
        "negatives": len(pairs) - positives,
        "auto_precision": round(tp / (tp + fp), 4) if tp + fp else 1.0,
        "auto_recall_same_language": round(same_lang_auto / same_lang_pos, 4)
        if same_lang_pos
        else 0.0,
        "candidate_recall_all": round(cand_tp / (cand_tp + cand_fn), 4) if positives else 0.0,
        "false_auto": false_auto,
        "missed_candidates": missed,
    }
